"""Game configuration constants."""

WIDTH, HEIGHT = 960, 540
FPS = 60

ROOM_LIVING = "Living Room"
ROOM_BATH = "Bathroom"

PLAYER_SPEED = 190
PLAYER_SIZE = 18

METER_MAX = 100
HUNGER_DRAIN = 0.75  # per minute
THIRST_DRAIN = 1.05  # per minute
SANITY_DRAIN = 0.55  # per minute
SANITY_LOW = 35

HUNGER_DEATH = 0
THIRST_DEATH = 0
SANITY_DEATH = 0

TV_SANITY_GAIN = 6.0
FAN_SANITY_GAIN = 3.5

NOISE_DECAY = 6.0  # per minute
NOISE_FROM_TV = 10.5
NOISE_FROM_FAN = 6.0
NOISE_FROM_SINK = 16.0

BREACH_BASE = 0.02  # base per second
BREACH_TV_BONUS = 0.012
BREACH_FAN_BONUS = 0.007
BREACH_MOVE_BONUS = 0.015
BREACH_CURSE_BONUS = 0.04

HALLUCINATION_BASE = 0.03

DAY_LENGTH = 140.0  # seconds per night
WIN_NIGHTS = 3

GROUNDING_COOLDOWN = 8.0
GROUNDING_WINDOW = 60.0
GROUNDING_BASE_GAIN = 14.0
GROUNDING_BASE_THIRST_COST = 6.0

LIQUID_COOLDOWN = 22.0
LIQUID_CURSE_TIME = 35.0
LIQUID_FREEZE_TIME = 18.0
LIQUID_TENTACLE_THRESHOLD = 3

SAFE_ROOM_HOLD = 8.0

# Colors
BLACK = (12, 12, 14)
WHITE = (240, 240, 240)
GRAY = (90, 90, 90)
LIGHT_GRAY = (150, 150, 150)
RED = (210, 60, 60)
GREEN = (70, 180, 90)
BLUE = (80, 120, 220)
YELLOW = (220, 200, 80)
PURPLE = (150, 90, 160)

# Asset names
ASSET_PLAYER = "player.png"
ASSET_DEAD_GIRL = "monster_dead_girl.png"
ASSET_TENTACLE = "monster_tentacle.png"
ASSET_HALLUCINATION = "monster_hallucination.png"
ASSET_TV = "tv.png"
ASSET_FAN = "fan.png"
ASSET_DOOR = "door.png"
ASSET_WINDOW = "window.png"
ASSET_VENT = "vent.png"
ASSET_MIRROR = "mirror.png"
ASSET_SINK = "sink.png"
ASSET_JUMPSCARE_GIRL = "jumpscare_girl.png"
ASSET_JUMPSCARE_TENTACLE = "jumpscare_tentacle.png"
